# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Configuration.UI'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(729, 563)
        self.gridLayout = QtWidgets.QGridLayout(Configuration)
        self.gridLayout.setObjectName("gridLayout")
        self.groupProject = QtWidgets.QGroupBox(Configuration)
        self.groupProject.setObjectName("groupProject")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupProject)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtLocalXml = QtWidgets.QLineEdit(self.groupProject)
        self.txtLocalXml.setObjectName("txtLocalXml")
        self.gridLayout_2.addWidget(self.txtLocalXml, 1, 0, 1, 1)
        self.txtDatabasesPath = QtWidgets.QLineEdit(self.groupProject)
        self.txtDatabasesPath.setObjectName("txtDatabasesPath")
        self.gridLayout_2.addWidget(self.txtDatabasesPath, 0, 0, 1, 1)
        self.btnDatabasePath = QtWidgets.QPushButton(self.groupProject)
        self.btnDatabasePath.setObjectName("btnDatabasePath")
        self.gridLayout_2.addWidget(self.btnDatabasePath, 0, 1, 1, 1)
        self.btnLocalXml = QtWidgets.QPushButton(self.groupProject)
        self.btnLocalXml.setObjectName("btnLocalXml")
        self.gridLayout_2.addWidget(self.btnLocalXml, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupProject, 0, 0, 1, 1)
        self.groupFirebird = QtWidgets.QGroupBox(Configuration)
        self.groupFirebird.setObjectName("groupFirebird")
        self.gridLayout.addWidget(self.groupFirebird, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "Configuration"))
        self.groupProject.setTitle(_translate("Configuration", "Projeto"))
        self.txtLocalXml.setPlaceholderText(_translate("Configuration", "Caminho arquivo local.xml"))
        self.txtDatabasesPath.setPlaceholderText(_translate("Configuration", "Caminho dos bancos"))
        self.btnDatabasePath.setText(_translate("Configuration", "Procurar"))
        self.btnLocalXml.setText(_translate("Configuration", "Procurar"))
        self.groupFirebird.setTitle(_translate("Configuration", "Firebird"))
